package io.hangga;

// Press Shift twice to open the Search Everywhere dialog and type `show whitespaces`,
// then press Enter. You can now see whitespace characters in your code.
public class Main {
    public static void main(String[] args) {
        String userDir = System.getProperty("user.dir");
        //String template = userDir + "/Template-Undangan-H.docx";
        String template = userDir + "/template.docx";
        String outputPath = userDir + "/output.docx";

        String[] names = {
                "Adiyanto",
                "Adnan Dani Pratama",
                "Afit",
                "Agung Rintoko",
                "Agus Catur",
                "Agus Suwarno Ja-az",
                "Akhadi Nugroho",
                "Ali Sukarno",
                "Alis Suyanto (RT.15)",
                "Amrul",
                "Anggri",
                "Anjas",
                "Arif Basuki",
                "Arkan",
                "Bagas Yudyanto",
                "Bagus Candra",
                "Bambang Supriyatna",
                "Basuki Yoso S",
                "Budi Cahyo Nugroho",
                "Drs. Agus Saparudin",
                "Drs. Agus Saparudin",
                "Dzaki David",
                "Eka Nuryanto",
                "Endartanto",
                "Faisal Alaudin",
                "Fathoni Siraj",
                "Febrianto Yuwono",
                "H. Budi Mulyo",
                "H. Hudono",
                "H. Sudarman",
                "H. Sudirman Sy",
                "Hanafi",
                "Hangga Aji Sayekti",
                "Henry Handoko",
                "Heri Supriyanta",
                "Herman",
                "Hidayat Sugiharto",
                "Ibnu Trisnawan",
                "Ibu Sudewi",
                "Imam Wicaksono.",
                "Ipul bin Fakhrul",
                "Isham bin Fakhrul",
                "Ivan",
                "Joko Setiono",
                "Juni",
                "Kiki",
                "Kuswardi",
                "Legino",
                "Lilik Hestu",
                "Lukman",
                "M Yusri Ilyas",
                "M. Arifin",
                "M. Fakhrudin",
                "M. Iqbal",
                "M. Iwan Suranto",
                "M. Jakfar Effendi",
                "M. Masykur Effendi",
                "M. Tri Wahyuno",
                "Marno",
                "Maryono",
                "Muryono",
                "Muszeni",
                "Nandar (RT.14)",
                "Narji Mulyono",
                "Ngadiono (RT.14)",
                "Ngahidin",
                "Nur Agus Jualifan",
                "Paeran M",
                "Pamu",
                "Parjono",
                "Parno",
                "Prapto Nugroho",
                "Ragil",
                "Ragil",
                "Raharjo Thole",
                "Rahmat Budi S",
                "Rahmawan Tri Yuwono",
                "Rahniadi/ Adi Kecil",
                "Refli Wulanto",
                "Reza",
                "Risky Budianto",
                "Romaidi",
                "Roni Firstkhul Azis",
                "Sarwana",
                "Sigit Putra S",
                "Slamet Windarto",
                "Sudaryanto",
                "Sugeng Sutrisno",
                "Sugiyanto",
                "Sujarwoto",
                "Sukasman",
                "Sukidjan",
                "Sukrisno",
                "Sukron",
                "Supriyanto (RT.14)",
                "Suroyo",
                "Susanto Y",
                "Sutrianto",
                "Suwardi",
                "Suwardjono M",
                "Suyatiman",
                "Syarif Deva",
                "Untung Sarwondono",
                "Wachid Sudarjo",
                "Wagiman PG",
                "Wahyu Jamaludin",
                "Wahyu Widayat",
                "Waluyo Rt.14",
                "Wasipan",
                "Widodo RT. 14",
                "Wihendra",
                "Willy",
                "Wiwin Nana (RT.16)",
                "Yaya",
                "Yuli Priyanto",
                "Yusron",
        };

        new CopyContent().doing(template, outputPath, names.length, new OnCopyFinish() {
            @Override
            public void OnSuccess(String output) {
                new DocProcessor().doing(names, output, outputPath);
            }

            @Override
            public void OnError(String errMsg) {

            }
        });
    }


}